import { Providers } from "./providers";
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <main className="max-w-lg w-full h-screen mx-auto">
          {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
